### Cada línea será una obsevación

### Usaremos estos datos para entrenar nuestro modelo

### Usaremos la estadistica para que nuestro programa identifique la especie de la flor por sus medidas

### Daremos nuevas medidas a nuestro ordenador para que este identifique a que especie pertenecen

In [2]:
from sklearn.datasets import load_iris

iris = load_iris()

# Obtenemos unicamente las observaciones, los datos
print(iris.data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [3]:
# A qué especie corresponde cada observación
print(iris.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [4]:
# Para saber a qué numero equivale cada especie
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [5]:
print(type(iris.target))

<class 'numpy.ndarray'>


In [6]:
# Comprobamos que el numero de observaciones coincida con el numero de target
print(iris.data.shape)

# 150 Observaciones, 4 Características

(150, 4)


In [7]:
print(iris.target.shape)

# 150 Observaciones

# Coincide, podemos continuar

(150,)


## Importing KNN

### K nearest neighbours
### Cuando representamos los datos siempre en el medio se entremezclan, si tenemos una nueva observacion y tenemos que decir a que especie pertenece lo que hace este algoritmo es coger los vecinos más cercanos, evaluarlos y respecto a estos tomar una decisión.
### Tomaremos k vecinos, siendo k definida por nosotros; definir correctamente el valor de k es algo muy importante porque afecta a la clasificación.

In [12]:
# Cuidado con la gramática

from sklearn.neighbors import KNeighborsClassifier

# Le pasamos un valor de k, que luego perfeccionaremos.

knn = KNeighborsClassifier(n_neighbors=1)

In [13]:
# X es comun usarla para los datos; y para el target

X = iris.data
y = iris.target

In [14]:
# Usaremos la funcion fit() para entrenar
knn.fit(X,y)

KNeighborsClassifier(n_neighbors=1)

In [18]:
# Hacemos nuestra primera prediccion, devuelve el valor target, en este caso 0, 1 o 2.
print(knn.predict( [ [5.5, 3.3,  5.5, 1.7] ] ))

[2]


## Dividiremos el dataset en dos, una mitad será usada para entrenar el modelo y la otra para testearlo

In [36]:
from sklearn.model_selection import train_test_split

# X_train se usara para entrenar el modelo y X_test para testearlo, de la misma forma se hará con y
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42) 
# 25% de los datos para testear, 75% para entrenar
# Muchas veces queremos comparar el comportamiento de varios modelos para seleccionar el mejor, para ello estableceremos un
# valor random para que siempre salga lo mismo

In [37]:
print(X_train)

[[6.3 2.7 4.9 1.8]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.1 3.3 1.7 0.5]
 [5.6 2.7 4.2 1.3]
 [5.1 3.4 1.5 0.2]
 [5.7 3.  4.2 1.2]
 [7.7 3.8 6.7 2.2]
 [4.6 3.2 1.4 0.2]
 [6.2 2.9 4.3 1.3]
 [5.7 2.5 5.  2. ]
 [5.5 4.2 1.4 0.2]
 [6.  3.  4.8 1.8]
 [5.8 2.7 5.1 1.9]
 [6.  2.2 4.  1. ]
 [5.4 3.  4.5 1.5]
 [6.2 3.4 5.4 2.3]
 [5.5 2.3 4.  1.3]
 [5.4 3.9 1.7 0.4]
 [5.  2.3 3.3 1. ]
 [6.4 2.7 5.3 1.9]
 [5.  3.3 1.4 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 2.4 3.8 1.1]
 [6.7 3.  5.  1.7]
 [4.9 3.1 1.5 0.2]
 [5.8 2.8 5.1 2.4]
 [5.  3.4 1.5 0.2]
 [5.  3.5 1.6 0.6]
 [5.9 3.2 4.8 1.8]
 [5.1 2.5 3.  1.1]
 [6.9 3.2 5.7 2.3]
 [6.  2.7 5.1 1.6]
 [6.1 2.6 5.6 1.4]
 [7.7 3.  6.1 2.3]
 [5.5 2.5 4.  1.3]
 [4.4 2.9 1.4 0.2]
 [4.3 3.  1.1 0.1]
 [6.  2.2 5.  1.5]
 [7.2 3.2 6.  1.8]
 [4.6 3.1 1.5 0.2]
 [5.1 3.5 1.4 0.3]
 [4.4 3.  1.3 0.2]
 [6.3 2.5 4.9 1.5]
 [6.3 3.4 5.6 2.4]
 [4.6 3.4 1.4 0.3]
 [6.8 3.  5.5 2.1]
 [6.3 3.3 6.  2.5]
 [4.7 3.2 1.3 0.2]
 [6.1 2.9 4.7 1.4]
 [6.5 2.8 4.6 1.5]
 [6.2 2.8 4.8 1.8]
 [7.  3.2 4.

In [38]:
print(X_train.shape)# En vez de 150 hay 112 observaciones (para entrenar), estas son seleccionadas de forma aleatoria

(90, 4)


In [39]:
print(X_test.shape)# Testeará con 38 observaciones

(60, 4)


In [40]:
knn.fit(X_train, y_train)

predictions = knn.predict(X_test)

print(predictions)

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0 0 0 2 1 1 0 0 1 1 2 1 2 1 2 1 0 2 1 0 0 0 1]


In [41]:
print(y_test)# Aquí tenemos las "respuestas correctas"

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0 0 0 2 1 1 0 0 1 2 2 1 2 1 2 1 0 2 1 0 0 0 1]


In [42]:
from sklearn import metrics

# Esto nos da el porcentaje de acierto de nuestro modelo

performance = metrics.accuracy_score(y_test, predictions)

print(performance)

0.9833333333333333
